<?php

namespace ContainerYL3xVui;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V9QHLKRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V9QHLKR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V9QHLKR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Api\\RestauranteController::index' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Api\\RestauranteController::index()', 'getRestauranteControllerindexService', true],
            'App\\Controller\\Api\\RestauranteController::create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Api\\RestauranteController::create()', 'getRestauranteControllercreateService', true],
            'App\\Controller\\Api\\RestauranteController::show' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Api\\RestauranteController::show()', 'getRestauranteControllershowService', true],
            'App\\Controller\\Api\\RestauranteController::update' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Api\\RestauranteController::update()', 'getRestauranteControllerupdateService', true],
            'App\\Controller\\Api\\RestauranteController::delete' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Api\\RestauranteController::delete()', 'getRestauranteControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Api\\RestauranteController:index' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Api\\RestauranteController::index()', 'getRestauranteControllerindexService', true],
            'App\\Controller\\Api\\RestauranteController:create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Api\\RestauranteController::create()', 'getRestauranteControllercreateService', true],
            'App\\Controller\\Api\\RestauranteController:show' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Api\\RestauranteController::show()', 'getRestauranteControllershowService', true],
            'App\\Controller\\Api\\RestauranteController:update' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Api\\RestauranteController::update()', 'getRestauranteControllerupdateService', true],
            'App\\Controller\\Api\\RestauranteController:delete' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Api\\RestauranteController::delete()', 'getRestauranteControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Api\\RestauranteController::index' => '?',
            'App\\Controller\\Api\\RestauranteController::create' => '?',
            'App\\Controller\\Api\\RestauranteController::show' => '?',
            'App\\Controller\\Api\\RestauranteController::update' => '?',
            'App\\Controller\\Api\\RestauranteController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Api\\RestauranteController:index' => '?',
            'App\\Controller\\Api\\RestauranteController:create' => '?',
            'App\\Controller\\Api\\RestauranteController:show' => '?',
            'App\\Controller\\Api\\RestauranteController:update' => '?',
            'App\\Controller\\Api\\RestauranteController:delete' => '?',
        ]);
    }
}
