<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYL3xVui\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYL3xVui/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYL3xVui.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYL3xVui\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYL3xVui\App_KernelDevDebugContainer([
    'container.build_hash' => 'YL3xVui',
    'container.build_id' => '5b916918',
    'container.build_time' => 1753970267,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYL3xVui');
