<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], [], []],
    '_wdt_stylesheet' => [[], ['_controller' => 'web_profiler.controller.profiler::toolbarStylesheetAction'], [], [['text', '/_wdt/styles']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'api_restaurantes_index' => [[], ['_controller' => 'App\\Controller\\Api\\RestauranteController::index'], [], [['text', '/api/restaurantes']], [], [], []],
    'api_restaurantes_create' => [[], ['_controller' => 'App\\Controller\\Api\\RestauranteController::create'], [], [['text', '/api/restaurantes']], [], [], []],
    'api_restaurantes_show' => [['id'], ['_controller' => 'App\\Controller\\Api\\RestauranteController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
    'api_restaurantes_update' => [['id'], ['_controller' => 'App\\Controller\\Api\\RestauranteController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
    'api_restaurantes_delete' => [['id'], ['_controller' => 'App\\Controller\\Api\\RestauranteController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
    'frontend_home' => [[], ['_controller' => 'App\\Controller\\FrontendController::home'], [], [['text', '/']], [], [], []],
    'App\Controller\Api\RestauranteController::index' => [[], ['_controller' => 'App\\Controller\\Api\\RestauranteController::index'], [], [['text', '/api/restaurantes']], [], [], []],
    'App\Controller\Api\RestauranteController::create' => [[], ['_controller' => 'App\\Controller\\Api\\RestauranteController::create'], [], [['text', '/api/restaurantes']], [], [], []],
    'App\Controller\Api\RestauranteController::show' => [['id'], ['_controller' => 'App\\Controller\\Api\\RestauranteController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
    'App\Controller\Api\RestauranteController::update' => [['id'], ['_controller' => 'App\\Controller\\Api\\RestauranteController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
    'App\Controller\Api\RestauranteController::delete' => [['id'], ['_controller' => 'App\\Controller\\Api\\RestauranteController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
    'App\Controller\FrontendController::home' => [[], ['_controller' => 'App\\Controller\\FrontendController::home'], [], [['text', '/']], [], [], []],
];
